// client/webapp/src/components/WatchNext/index.tsx
import { useNavigate } from "react-router-dom";
import useFetch from "../../hooks/useFetch";
import Carousel from "../Carousel";

type WatchStatus = {
  watchStatusId: string;
  relationId: string;
  relationType: string;
  timestamp: string;
};

const WatchNext: React.FC = () => {
  const navigate = useNavigate();
  const { data, error } = useFetch<WatchStatus[]>(
    "http://192.168.3.16:3000/api/watchStatus"
  );

  if (error || !data?.length) return <></>;

  const handleOnClick = (row: WatchStatus) => {
    if (row.relationType === "EPISODE") {
      navigate(`/watch/episode/${row.relationId}?timestamp=${row.timestamp}`);
    }
    if (row.relationType === "MOVIE") {
      navigate(`/watch/movieId/${row.relationId}?timestamp=${row.timestamp}`);
    }
  };

  return (
    <Carousel
      label="Watch Next"
      items={data ?? []}
      renderName={(item: WatchStatus) => item.watchStatusId}
      onItemClick={handleOnClick}
    />
  );
};

export default WatchNext;

// client/web/src/components/watchNext.svelte
<script lang="ts">
	import Carousel from './carousel.svelte';
	import { apiData, watchNext } from '$lib/watchNextStore';
	import { onMount } from 'svelte';
	import type { CarouselOptions } from '$lib/carousel';

	onMount(async () => {
		fetch('http://192.168.3.16:3000/api/watchStatus')
			.then((response) => response.json())
			.then((data) => {
				console.log(data);
				apiData.set(data);
			})
			.catch((error) => {
				console.log(error);
				return [];
			});
	});

	const getWatchNextURL = (row: Record<string, unknown>) => {
		if (row.relationType === 'EPISODE') return `/watch/episode`;
		if (row.relationType === 'MOVIE') return `/watch/movie`;
		throw new Error(`unknown type => ${row.relationType}`);
	};

	const getParams = (row: Record<string, unknown>) => {
		return `timestamp=${row.timestamp}`;
	};

	export const options: CarouselOptions = {
		idKey: 'relationId',
		nextRoute: getWatchNextURL,
		getParams,
		titleKey: ''
	};
</script>

{#if $watchNext.length}
	<h1>Watch Next</h1>
	<div style="display: flex; flex-direction: column">
		<Carousel {options} rows={$watchNext} />
	</div>
{/if}
